if process?.env?.LOGENTRIES_TOKEN
  _log = require('node-logentries').logger
    token:process.env.LOGENTRIES_TOKEN
  log = 
    debug: ->
      _log.debug arguments...
      console.log arguments...
    err: ->
      _log.err arguments...
      console.error arguments...
    info: ->
      _log.info arguments...
      console.log arguments...
    log: ->
      _log.log arguments...
      console.log arguments...
  console.log "logged to logentries"
else
  log =
    debug: console.log
    err: console.error
    info: console.info
    log: console.log

module.exports = log